InternetShopDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from InternetShopDjango import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views, views_cart
from . import views_auth
from . import views_cabinet,views_users,views_telegram,views_chatId


app_name = 'shop'
urlpatterns = [
    path('', views.main, name='main'),
    path('detail/<int:pk>/', views.detail, name='detail'),

    #Успешный заказ

    path('secsseful/',views_cart.secsseful, name='secsseful'),


    path('add_product/', views.add_product, name='add_product'),

    path('delete_product/<int:product_id>/',views.delete_product, name='delete_product'),

    path('edit_product/<int:product_id>/',views.edit_product,name='edit_product'),


    path('users/',views_users.users,name='users'),



    path('admin_panel/',views.admin_panel,name='admin_panel'),



    path('cabinet/<str:username>/', views_cabinet.cabinet_views, name='cabinet'),

    path('create_order_cart/<str:username>/', views_cabinet.create_order_card, name='create_order_cart'),

    path('order/', views_cart.order, name='order'),

    path('order_detail/<int:pk_order>/', views_cart.order_detail, name='order_detail'),

    path('order_delete/<int:pk_order>/', views_cart.order_delete, name='order_delete'),



    path('delete_cartItem/<str:username>/<int:cart_id>/', views_cabinet.delete_from_cabinet_cart, name='delete_cartItem'),


    path('subscribe_product/<int:pk>/<str:username>/', views.subscribe_product, name='subscribe_product'),

    path('unsubscribe_product/<int:pk>/<str:username>/', views.unsubscribe_product, name='unsubscribe_product'),


    path('add_to_cart/<str:username>/<int:product_id>/', views_cart.add_to_cart, name='add_to_cart'),

    path('edit_you_chatId/<str:username>',views_chatId.edit_you_chatId,name='edit_you_chatId'),


    path('signup/', views_auth.signup, name='signup'),
    path('login/', views_auth.login, name='login'),
    path('logout/', views_auth.logout, name='logout'),
]

shop/models.py
import decimal
import os

from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.contrib.auth.models import User
from .bot import send_message_to_user
# Create your models here.
def upload_to(instance, filename):
    # Если instance не сохранен в базе данных или не существует, возвращаем дефолтный путь
    print(f'[{instance}] - {filename}')
    if not instance or not instance.pk:
        return f"detail/image/{filename}"

    # Получаем расширение файла
    filename_base, filename_ext = os.path.splitext(filename)

    # Получаем объект ProductImage, связанный с данным товаром
    product_image = ProductImage.objects.filter(product=instance).first()

    # Определяем номер следующего изображения
    next_photo_number = 1 if not product_image else ProductImage.objects.filter(product=instance).count() + 1

    # Возвращаем путь сохранения файла
    return f"{instance.name}/{instance.name}_{next_photo_number}{filename_ext}"




class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    description = models.TextField(max_length=1000,default='Описание')

    def __str__(self):
        return self.name

    def subscribe(self,user):
        Subscriber.objects.get_or_create(user=user,product=self)


    def unsubscribe(self,user):
        Subscriber.objects.filter(user=user,product=self).delete()

    def notify(self):
        subscribers = Subscriber.objects.filter(product = self)



        for sub in subscribers:
            Message.objects.create(title="!!!",text="Обновление!",user=sub.user)
            try:
                chatId = Telegramid.objects.get(user=sub.user)
                if chatId:
                    send_message_to_user(chatId.chat_id, "Товар из списка ваших подписок обновился!")
            except ObjectDoesNotExist:
                print(f"Telegram ID не найден для пользователя: {sub.user}")
            except Exception as e:
                print(f"Ошибка при уведомлении пользователя: {sub.user}, ошибка: {e}")


class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name='images', on_delete=models.CASCADE)
    product_images = models.ImageField(upload_to='detail')


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

#model for podpisoti
class Subscriber(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    class Meta:
        unique_together = (('user', 'product'),)


class Cart(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    #Проверка наличие чего либо в корзине
    def has_items(self):
        return self.items.exists()
    def create_order(self):
        order = Order.objects.create(user=self.user, total_price= 0.00)
        total_price = decimal.Decimal(0.00)
        for item in self.items.all():
            order_item = OrderItem.objects.create(
                order=order,
                product=item.product,
                quantity=item.quantity,
                price=item.product.price
            )

            price = decimal.Decimal(order_item.price)
            quantity = decimal.Decimal(order_item.quantity)


            total_price += price*quantity

        order.total_price = total_price
        order.save()
        self.items.all().delete()
        return order


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)


class Order(models.Model):
    create = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total_price = models.DecimalField(max_digits=10, decimal_places=2,default=0.00)

    def __str__(self):
        return f' Заказ-{self.id}.От {self.user}'

class OrderItem(models.Model):
    order = models.ForeignKey(Order,related_name='items',on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.quantity}-{self.product.name}"


class Telegramid(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    chat_id = models.CharField(max_length=100,unique=True)

    def __str__(self):
        return f'{self.user.username} - {self.chat_id}'






class Message(models.Model):
    title = models.CharField(max_length=255)
    text = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

templates/adminPanel.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Панель{% endblock %}
{% block classheader %}header-my-two{% endblock %}
{% block colorone %}black{% endblock %}
{% block brand %}brand2{% endblock %}
{% block colortwo %}black{% endblock %}
{% block content %}

<h2 class="text-h" style="text-align:center; margin-top:20px;">Админ панель</h2>

<div class="container card shadow p-3 mb-5 bg-body rounded" style="margin-top:30px;">
    <div class="d-grid gap-2">
        <a class="btn btn-outline-dark" type="button" href="{% url 'shop:order' %}" style="margin-bottom:10px; margin-top:10px;"><i class="bi bi-list-ul"></i><span>Заказы</span></a>
        <a class="btn btn-outline-dark" type="button" href="{% url 'shop:add_product' %}" style="margin-bottom:10px;"><i class="fa-solid fa-plus"></i>Пополнить товары</a>
        <a class="btn btn-outline-dark" type="button" href="{% url 'shop:users' %}" style="margin-bottom:10px;"><i class="fa-solid fa-users"></i>  Пользователи</a>
        <a class="btn btn-outline-dark" type="button" href="#" style="margin-bottom:10px;">Админ панель</a>
        <a class="btn btn-outline-dark" type="button" href="#" style="margin-bottom:10px;">Админ панель</a>


    </div>
</div>


{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}title{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Caveat:wght@400..700&family=Jacquard+24&family=Poetsen+One&display=swap">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <style>
        .btn-primary {
            background-color: #ECD06C;
            color: white;
            border: none;
        }

        .btn-primary:hover {
            background-color: #ECD06C
            color: white;
        }
    </style>

</head>
<body>
<header class='site-header {% block classheader %}header-my{% endblock %}' style="border-bottom: 2px solid {% block colorone %}white{% endblock %}; display: flex; justify-content: space-between; align-items: center;">
    <a class ="my_brand_" href="{% url 'shop:main' %}"><h1 class="{% block brand %}brand{% endblock %}">AFRODITA</h1></a>
    <nav>
        {% if user.is_authenticated %}
            <button type="button" class="btn" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight"><i class="fa-solid fa-bars" style="font-size:30px; color:{% block colortwo %}#F1ECE9{% endblock %};"></i></button>
        {% else %}
            <a class="nav-link active" aria-current="page" href="{% url 'shop:signup' %}">Регистрация</a>
            <a class="nav-link" href="{% url 'shop:login' %}">Вход</a>
        {% endif %}
    </nav>
</header>
    <div style="margin-bottom: 50rem">
        {% block content %}
        {% endblock %}
    </div>

    <!--Offcanvas-->
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel" style={% block style %}"background-color: rgba(255, 255, 255, 0.7);"{% endblock %}>
        <div class="offcanvas-header">
            <h5 id="offcanvasRightLabel">{{ user.username }}</h5>
            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            {% if user.username %}
                <div class="d-grid gap-2">
                <a class="btn" type="button" href="{% url 'shop:cabinet' user.username %}" style="text-align:left;padding-left:20px;"><i class="fa-solid fa-house"></i>  Кабинет</a>
                {% if user.is_superuser %}
                    <a class="btn" type="button" href="{% url 'shop:admin_panel' %}" style="text-align:left;padding-left:20px;"><i class="fa-solid fa-hammer"></i> Админ панель</a>

                {% endif %}
                <a class="btn" type="button" href="{% url 'shop:logout' %}" style="text-align:left; color:red;padding-left:20px;"><i class="fa-solid fa-door-open"></i> Выход</a>
            </div>
            {% endif %}
        </div>
    </div>


    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/cabinet.html
{% extends 'base.html' %}
{% block title %}Кабинет{% endblock %}

{% block classheader %}header-my-two{% endblock %}
{% block colorone %}black{% endblock %}
{% block brand %}brand2{% endblock %}
{% block colortwo %}black{% endblock %}


{% block content %}

<style>
    body {
        overflow-x: hidden; /* Отключает горизонтальную прокрутку для всей страницы */
    }
</style>

<div class="row">
    <div class="col">
<div class="card border-dark mb-3 shadow-lg" style="width: 100rem; margin-left: 8rem; height:50rem; margin-top: 5rem; height:auto;">
    <div class="card-header" style="text-align: center">{{ user.username }}</div>
    <div class="card-body text-dark">
    <h5 class="card-title">{{ user.username }}</h5>
    <p class="card-text"></p>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">title</th>
              <th scope="col">text</th>
              <th scope="col">read</th>
            </tr>
          </thead>
          <tbody>
            {% for mess in message %}
                <tr>

                  <th scope="row">#</th>
                  <td>{{ mess.title }}</td>
                  <td>{{ mess.text|truncatechars:10 }}</td>
                  <td><i class="fa-solid fa-check"></i></td>

                </tr>
            {% endfor %}

          </tbody>
        </table>
    </div>
</div>
<div class="card border-dark mb-3 shadow-lg" style="max-width: 100rem; margin-left: 8rem; height:auto;">
    <div class="card-header" style="text-align: center">Подписки</div>
    <div class="card-body text-dark">
    <h5 class="card-title"></h5>

        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Product</th>
              <th scope="col">price</th>
              <th scope="col">delete</th>
            </tr>
          </thead>
          <tbody>
            {% for sub in subscribe %}
                <tr>

                  <th scope="row">#</th>
                  <td>{{ sub.product.name }}</td>
                  <td>{{ sub.product.price }}</td>
                  <td><a type="button" class="btn btn-danger" href="{% url 'shop:unsubscribe_product' sub.product.id user.username %}"><i class="fa-solid fa-minus"></i></a></td>

                </tr>
            {% endfor %}

          </tbody>
        </table>
    <p class="card-text"></p>
    </div>
</div>
<div class="card border-dark mb-3 shadow-lg" style="max-width: 100rem; margin-left: 8rem; height:auto;">
    <div class="card-header" style="text-align: center">Корзина</div>
    <div class="card-body text-dark">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Product</th>
              <th scope="col">quantity</th>
              <th scope="col">price</th>
              <th scope="col">delete</th>
            </tr>
          </thead>
          <tbody>
            {% for item in products_in_cart %}
                <tr>

                  <th scope="row">{{ item.number }}</th>
                  <td>{{ item.name }}</td>
                  <td>{{ item.quantity }}</td>
                  <td>{{ item.total_price }}</td>
                  <td><a type="button" class="btn btn-danger" href="{% url 'shop:delete_cartItem' username=user.username cart_id=item.id_cart %}"><i class="fa-solid fa-minus"></i></a></td>
                </tr>
            {% endfor %}
            <a href = '{% url "shop:create_order_cart" user.username %}' type="button" class="btn btn-dark">Заказать</a>

          </tbody>
        </table>
    </div>
</div>
</div>
    <div class="col" style="margin-top:80px;">
        <a type="button" href="{% url 'shop:edit_you_chatId' user.username %}" class="btn" style="position:fixed"><i class="fa-brands fa-telegram" style="font-size:50px"></i></a>
    </div>
    </div>




{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ product.name }}{% endblock %}

{% block classheader %}header-my-two{% endblock %}
{% block colorone %}black{% endblock %}
{% block brand %}brand2{% endblock %}
{% block colortwo %}black{% endblock %}

{% block content %}
<style>
    body {
        overflow-x: hidden; /* Отключает горизонтальную прокрутку для всей страницы */
    }

    .carousel-inner img, .single-image {
        width: 100%; /* Убедитесь, что изображения не выходят за пределы */
    }

    .container {
        max-width: 100%; /* Убедитесь, что контейнеры не превышают ширину экрана */
    }

    .carousel-container {
        max-width: 500px; /* Установите нужную максимальную ширину карусели */
        margin: 0 auto;  /* Центрирование карусели */
    }

    .carousel-inner img, .single-image {
        max-width: 100%;
        height: auto;
        cursor: pointer; /* Добавляем указатель при наведении на изображение */
    }

    /* Стили для модального окна */
    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        padding-top: 100px;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgb(0,0,0);
        background-color: rgba(0,0,0,0.9);
    }

    .modal-content {
        margin: auto;
        display: block;
        width: 80%;
        max-width: 700px;
    }

    #caption {
        margin: auto;
        display: block;
        width: 80%;
        max-width: 700px;
        text-align: center;
        color: #ccc;
        padding: 10px 0;
        height: 150px;
    }

    .close {
        position: absolute;
        top: 15px;
        right: 35px;
        color: #f1f1f1;
        font-size: 40px;
        font-weight: bold;
        transition: 0.3s;
    }

    .close:hover,
    .close:focus {
        color: #bbb;
        text-decoration: none;
        cursor: pointer;
    }

    .btn-primary {
    background-color: #ECD06C;
    color: white;
    border: none;
    }

    .btn-primary:hover {
        background-color: #ECD06C
        color: white;
    }
    .product-description {
        white-space: pre-line; /* Сохраняет пробелы и переносы строк */
    }
</style>


<div class="container">
    <div class="row">
        {% if product_images|length > 1 %}
        <div class="col-md-6">
            <div class="carousel-container">
                <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
                    <div class="carousel-indicators">
                        {% for image in product_images %}
                        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}" aria-current="true" aria-label="Slide {{ forloop.counter }}"></button>
                        {% endfor %}
                    </div>
                    <div class="carousel-inner">
                        {% for image in product_images %}
                        <div class="carousel-item {% if forloop.first %}active{% endif %}" data-bs-interval="10000">
                            <img src="{{ image.product_images.url }}" class="d-block w-100" alt="Slide {{ forloop.counter }}">
                        </div>
                        {% endfor %}
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
        </div>
        {% else %}
        <div class="col-md-6">
            <div class="image-container" style="text-align:center;">
                <img src="{{ product_images.0.product_images.url }}" class="single-image" alt="{{ product.name }}">
            </div>
        </div>
        {% endif %}
        <div class="col-md-6" style="margin-top:180px">
            <h2 class="text-detail-name">{{ product.name }}</h2>
            <h3 class="price">{{ product.price }}&#8376;</h3>
            <p style="color:gray;margin-top:30px">Описание:</p>
            <p style="text-align:left" id="product-description">{{ product.description }}</p>
            <script>
                document.addEventListener("DOMContentLoaded", function() {
                    var descriptionElement = document.getElementById("product-description");
                    var description = descriptionElement.innerText;
                    var formattedDescription = "";
                    var maxLength = 46; // Разделяем каждые 50 символов

                    for (var i = 0; i < description.length; i += maxLength) {
                        formattedDescription += description.substr(i, maxLength) + "<br>";
                    }

                    // Удаляем последний <br>
                    formattedDescription = formattedDescription.slice(0, -4);

                    // Обновляем содержимое элемента с новым описанием
                    descriptionElement.innerHTML = formattedDescription;
                });
            </script>
            <div>
                {% if user.username %}
                <a class="btn btn-primary m-3" href="{% url 'shop:add_to_cart' user.username product.id %}" type="button">В корзину</a>
                <a class="btn m-3" href='{% url "shop:subscribe_product" product.id user.username %}' type="button"><i class="fa-regular fa-heart" style="font-size:25px"></i></a>
                {% endif %}
                <br style="padding:0px;margin:0px">
                {% if user.is_superuser %}
                <a class="btn btn-primary m-3" href='{% url "shop:edit_product" product.id%}' type="button">Редактировать</a>
                <a class="btn m-3" href='{% url "shop:delete_product" product.id%}' type="button"><i class="fa-solid fa-trash" style="font-size:25px;color:#FA7C71;"></i></a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- Модальное окно -->
<div id="myModal" class="modal">
    <span class="close">&times;</span>
    <img class="modal-content" id="img01">
    <div id="caption"></div>
</div>

<script>
    var modal = document.getElementById("myModal");

    var img = document.querySelectorAll(".carousel-inner img, .single-image");
    var modalImg = document.getElementById("img01");
    var captionText = document.getElementById("caption");

    img.forEach(function(image) {
        image.onclick = function() {
            modal.style.display = "block";
            modalImg.src = this.src;
            captionText.innerHTML = this.alt;
        }
    });

    var span = document.getElementsByClassName("close")[0];

    span.onclick = function() {
        modal.style.display = "none";
    }

    modal.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>
{% endblock %}
{% block style %}"background-color: rgba(255, 255, 255, 1);"{% endblock %}

templates/order.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Заказы{% endblock %}
{% block classheader %}header-my-two{% endblock %}
{% block colorone %}black{% endblock %}
{% block brand %}brand2{% endblock %}
{% block colortwo %}black{% endblock %}
{% block content %}


<div class="container mt-3">
    <h2 class="text-h" style="text-align:center;">Заказы</h2>
    <div class="row row-cols-1 row-cols-md-3 g-4 mt-3">
    {% for item in order %}
        <div class="col">
            <div class="card border-dark p-3 mb-5 bg-body rounded" style="width: 18rem;">
              <div class="card-body">
                <h5 class="card-title" style="text-align:center;">Заказ от: {{ item.user }}</h5>
                  <div class="d-grid gap-2">
                      <a class="btn btn-outline-dark" type="button" href="{% url 'shop:order_detail' item.id %}"><i class="fa-solid fa-info"></i></a>
                      <a class="btn btn-outline-dark" type="button" href="{% url 'shop:order_delete' item.id %}"><i class="fa-solid fa-trash" style="font-size:25px;color:#FA7C71;"></i></a>
                  </div>
              </div>
            </div>
       </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

templates/product_edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Изменяем{% endblock %}
{% block classheader %}header-my-two{% endblock %}
{% block colorone %}black{% endblock %}
{% block brand %}brand2{% endblock %}
{% block colortwo %}black{% endblock %}
{% block content %}


   <!-- <h1>Edit MyModel</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-outline-dark" type="submit">Save</button>
    </form>-->

    <h2 class="text-h mt-3" style="text-align:center">Изменить продукт</h2>

<div class="container card shadow p-3 mb-5 bg-body rounded" style="margin-top:30px;">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!--{{ product_form.as_p }}
        <input type="hidden" name="csrfmiddlewaretoken" value="kuNeDlhDGEU7ukbQhsgGfAPKYM5s2l8ZcbN99BdFvxyenSOc18vr9FLMZ2EAkUEd">-->

        <div class="mb-3">
            <label for="id_name" class="form-label text-style-form">Name:</label>
            <input type="text" name="name" class="form-control" value="{{ name }}" maxlength="255" required="" id="id_name">
        </div>

        <div class="mb-3">
            <label for="id_description" class="form-label text-style-form">description:</label>
            <textarea class="form-control" name="description" id="id_description" placeholder="Required example textarea" required="">{{ description }}</textarea>
        </div>

        <div class="mb-3">
            <label for="id_price" class="form-label text-style-form">Price:</label>
            <input type="number" class="form-control" name="price" value="{{ price }}" step="0.01" required="" id="id_price">
        </div>

        <div style="margin-top:30px;">
            <h2 class="text-h" style="text-align:center;">Фото</h2>
            {{ image_formset.management_form }}
            {% for form in image_formset %}
                {{ form.as_p }}
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-dark"><i class="fa-solid fa-floppy-disk"></i> Сохранить</button>
    </form>
</div>


{% endblock %}

<!--<form method="post" enctype="multipart/form-data">
        <input type="hidden" name="csrfmiddlewaretoken" value="kuNeDlhDGEU7ukbQhsgGfAPKYM5s2l8ZcbN99BdFvxyenSOc18vr9FLMZ2EAkUEd">
        <p>
    <label for="id_name">Name:</label>
    <input type="text" name="name" value="Сумки Розовые" maxlength="255" required="" id="id_name">


  </p>


  <p>
    <label for="id_price">Price:</label>
    <input type="number" name="price" value="10001.00" step="0.01" required="" id="id_price">




  </p>

        <h2>Product Images</h2>
        <input type="hidden" name="images-TOTAL_FORMS" value="3" id="id_images-TOTAL_FORMS"><input type="hidden" name="images-INITIAL_FORMS" value="2" id="id_images-INITIAL_FORMS"><input type="hidden" name="images-MIN_NUM_FORMS" value="0" id="id_images-MIN_NUM_FORMS"><input type="hidden" name="images-MAX_NUM_FORMS" value="10" id="id_images-MAX_NUM_FORMS">

            <p>
    <label for="id_images-0-product_images">Product images:</label>
    На данный момент: <a href="/photo/detail/images2.jpeg">detail/images2.jpeg</a><br>
Изменить:
<input type="file" name="images-0-product_images" accept="image/*" id="id_images-0-product_images">


  </p>


  <p>
    <label for="id_images-0-DELETE">Удалить:</label>
    <input type="checkbox" name="images-0-DELETE" id="id_images-0-DELETE">


      <input type="hidden" name="images-0-id" value="1" id="id_images-0-id"><input type="hidden" name="images-0-product" value="1" id="id_images-0-product">

  </p>

            <p>
    <label for="id_images-1-product_images">Product images:</label>
    На данный момент: <a href="/photo/detail/154488818012575681_lPh605K.png">detail/154488818012575681_lPh605K.png</a><br>
Изменить:
<input type="file" name="images-1-product_images" accept="image/*" id="id_images-1-product_images">


  </p>


  <p>
    <label for="id_images-1-DELETE">Удалить:</label>
    <input type="checkbox" name="images-1-DELETE" id="id_images-1-DELETE">


      <input type="hidden" name="images-1-id" value="7" id="id_images-1-id"><input type="hidden" name="images-1-product" value="1" id="id_images-1-product">

  </p>

            <p>
    <label for="id_images-2-product_images">Product images:</label>
    <input type="file" name="images-2-product_images" accept="image/*" id="id_images-2-product_images">


  </p>


  <p>
    <label for="id_images-2-DELETE">Удалить:</label>
    <input type="checkbox" name="images-2-DELETE" id="id_images-2-DELETE">


      <input type="hidden" name="images-2-id" id="id_images-2-id"><input type="hidden" name="images-2-product" value="1" id="id_images-2-product">

  </p>


        <button type="submit">Save</button>
    </form>-->